# supabase基础信息
SUPABASE_URL: https://gsqhzvncrktdbnajsyxj.supabase.co
SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcWh6dm5jcmt0ZGJuYWpzeXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTEwMzU5ODgsImV4cCI6MjAyNjYxMTk4OH0.sZVnqX378QWEtdFEo4If3fNrpaIjFmPiRagy_-S_uHo
SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcWh6dm5jcmt0ZGJuYWpzeXhqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxMTAzNTk4OCwiZXhwIjoyMDI2NjExOTg4fQ.wgUq0pfO9TcdQS2fwDVaE3WTAbLp7s0M-6dqJmmEux8

# 接码账号密码
SMS_USERNAME: MY1830
SMS_PASSWORD: dddd1111

# 注册机密码
REGIST_PASSWORD: Opooo1830
